### ISSUE TITLE
bibtex broken in recent zola

### ISSUE THREAD

**Issue by csgordon** [adfaure/kodama-theme#13]
I'm new to Zola, using 0.17.2, which is what you get with the current installation instructions.

After failing for a while to get bibtex working in my attempt at my own site (though other aspects of the theme work very nicely so far), I tried to just confirm if I could get kodama-theme to work correctly by itself. Bibtex files are not read correctly.

Steps to reproduce:
- Clone this repository somewhere new
- Install zola; the latest instructions get version 0.17.2 on a Mac
- Enter the kodama-theme directory for this fresh checkout
- ```zola serve``` and go to the local url
- Navigate to the page for "paper1" by clicking its title in the list of recent publications

Expected results:
- I expect to see a page like https://adfaure.github.io/kodama-theme/publications/paper1/, which at present has the abstract and other details extracted from the bib file in the repository, and includes the bibtex itself on the page.

Observed results:
- The site builds and is served, but instead of expected behavior, I see the attached screenshot:
<img width="828" alt="Screenshot 2023-07-10 at 11 12 44 PM" src="https://github.com/adfaure/kodama-theme/assets/1105189/93c5b357-5dee-469b-92b8-a8aa270e5ae3">
The information that was extracted from the bib file in the demo site does not appear, nor does the actual bibtex itself.

I'm on a mac, with a fresh install of zola 0.17.2. Poking around the GH actions, I see the demo site appears to be built using nix, and the logs suggest the last build of the demo used 0.15.3 (https://github.com/adfaure/kodama-theme/actions/runs/4924207168/jobs/8796965946#step:4:219).

**Comment by adfaure** [comment]
Hello,

this is due to an error in the template example. Renaming your file the file with the big extension should cause it to be loaded and displayed.

I fixed the template here: https://github.com/adfaure/kodama-theme/commit/aa2a1b0775bd76493b362f9d485f01aa9ae10623

Let me know if it worked for you.

Thank for reporting the issue.

**Comment by csgordon** [comment]
This seems to work, both when trying to serve the template and when trying to build my own site! Thank you!
