### ISSUE TITLE
Link on author names

### ISSUE THREAD

**Issue by plafourc** [adfaure/kodama-theme#16]
Hi, I’m still working on my academic webpage...

In the list of publications, I would like to add a link on the authors’ names (so visitors can reach the webpages of my co-authors). Looking into the code I see a `links_allowed` variable that seems to be designed for this, but I can’t find how to use it in the docs.

Thanks :)

**Comment by adfaure** [comment]
Hi,

The `links_allowed` works with the [taxonomies](https://www.getzola.org/documentation/content/taxonomies/) feature of zola, and it will create a link that points inside your website.
I believe it has been added by Piotr.

For your use case, you can maybe override the authors macro (I don't know if it is possible with zola) to include your logic?

**Comment by plafourc** [comment]
Ok I see it’s no so simple then. I’ll figure it out don’t worry. Closing the issue. Thank you!

**Comment by adfaure** [comment]
Okay, good luck :)
